version: 2.0
jobs:
    build:
        docker:
            -image:mrc.microsoft.com/dotnet/core/sdk2.1
        steps:
            - checkout
            - run:
                name: Restore packages
                command:
                    dotnet restore
            - run:
                name:Build App
                command:
                    dotnet build
            - run:
                name: Test App
                command:
                    dotnet test